# Generated by Django 4.0.4 on 2022-05-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articletag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'ordering': ['-is_main', 'tag']},
        ),
    ]
