# Generated by Django 4.0.4 on 2022-05-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_articletag_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articletag',
            constraint=models.UniqueConstraint(fields=('article', 'tag'), name='some_unique_name'),
        ),
    ]
