# Generated by Django 4.0.4 on 2022-05-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articletag_some_unique_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'ordering': ['-is_main', '-tag']},
        ),
    ]
