# Generated by Django 4.0.4 on 2022-05-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_articletag_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'ordering': ['-is_main', '-tag']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
